pipeline{
  agent any
  environment {
    IMAGE_NAME = "anagaraj15/md-devops-mastercls:${GIT_COMMIT}"
    DOCKER_CREDS = credentials('docker-hub-creds')
  }
  stages{
    stage('Git-Checkout'){
      steps{
        git url:"https://github.com/anagaraj15/md-devops-mastercls.git",branch:"main"
      }
    }
    stage('Build'){
      steps{
        sh '''
          printenv
          pwd
          cd "BusGo web app"
          docker build -t ${IMAGE_NAME} .
        '''
      }
    }
    stage('testing the image'){
      steps{
        sh '''
          docker kill c8
          docker rm c8
          docker run -it -d --name c8 -e NG_CLI_ANALYTICS=false -p 9003:4200 ${IMAGE_NAME}
        '''
      }
    }
    stage('docker-hub-login'){
      steps{
        withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
          // some block
          sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
        }
        
      }
    }
    stage('pushing to registry'){
      steps{
         withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
          // some block
          sh '''
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            
            # 2. Re-tag the existing image to use the correct registry namespace
            # From: anagaraj15/md-devops-mastercls:d9a30b...
            # To:   anagaraj05/md-devops-mastercls:d9a30b...
            docker tag anagaraj15/md-devops-mastercls:${GIT_COMMIT} ${DOCKER_USERNAME}/md-devops-mastercls:${GIT_COMMIT}
            
            # 3. Push the corrected tag
            docker push ${DOCKER_USERNAME}/md-devops-mastercls:${GIT_COMMIT}
          '''
        }
        
      }
    }
  }
}