pipeline{
  agent any
  environment {
    IMAGE_NAME = "anagaraj15/md-devops-mastercls:${GIT_COMMIT}"
    DOCKER_CREDS = credentials('docker-hub-creds')
  }
  stages{
    stage('Git-Checkout'){
      steps{
        git url:"https://github.com/anagaraj15/md-devops-mastercls.git",branch:"main"
      }
    }
    stage('Build'){
      steps{
        sh '''
          printenv
          pwd
          cd "BusGo web app"
          docker build -t ${IMAGE_NAME} .
        '''
      }
    }
    stage('testing the image'){
      steps{
        sh '''
          docker kill c8
          docker rm c8
          docker run -it -d --name c8 -e NG_CLI_ANALYTICS=false -p 9003:4200 ${IMAGE_NAME}
        '''
      }
    }
    stage('docker-hub-login'){
      steps{
        withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
          // some block
          sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
        }
        
        // sh 'echo "$DOCKER_CREDS_PSW" | docker login -u "$DOCKER_CREDS_USR" --password-stdin'
      }
    }
    stage('pushing to registry'){
      steps{
        sh '''
          echo "$DOCKER_CREDS_PSW" | docker login -u "$DOCKER_CREDS_USR" --password-stdin
          docker push ${IMAGE_NAME}
        '''
      }
    }
  }
}