pipeline{
  agent any
  environment {
    IMAGE_NAME = 'anagaraj15/md-devops-mastercls:${GIT_COMMIT}'
  }
  stages{
    stage('Git-Checkout'){
      steps{
        git url:"https://github.com/anagaraj15/md-devops-mastercls.git",branch:"main"
      }
    }
    stage('Build'){
      steps{
        sh '''
          printenv
          pwd
          cd "BusGo web app"
          docker build -t ${IMAGE_NAME} .
        '''
      }
    }
  }
}